### ISSUE TITLE
Enhance validity duration print for granular durations

### ISSUE THREAD

**Issue by WorldThirteen** [PeculiarVentures/pv-certificates-viewer#116]
At the moment cert viewer shows certificate validity duration in days for short-lived certificates.

By the way for certificates with a validity of less than a day, the exact duration is not clear:
![image](https://user-images.githubusercontent.com/14346393/181498518-e328665b-ff71-4aeb-b4cf-7103328ea448.png)

It would be cool to enhance and have for example:
`0 days, 0 hours, 10 minutes` or just `10 minutes`

**Comment by donskov** [comment]
@WorldThirteen Changes added. Please try:
```
 - @peculiar/certificates-viewer-react@3.0.3
 - @peculiar/certificates-viewer@3.0.3
 ```
