### ISSUE TITLE
Show the public key type as a column in the certificate view

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/pv-certificates-viewer#12]
Knowing the public key type in the summary list would be useful:

| Name | Public Key | Fingerprint (SHA1) | Actions | Test URLs |
|------|------------|--------------------|---------|-----------|
|        |      |            |                    |         |           |

**Comment by donskov** [comment]
Fixed in https://github.com/PeculiarVentures/pv-certificates-viewer/pull/15
