### ISSUE TITLE
unable to resolve dependency tree for react ^18.2.0

### ISSUE THREAD

**Issue by pavsoldatov** [PeculiarVentures/pv-certificates-viewer#120]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/80415302/187735026-ad366929-3800-4139-8f4f-0ad7d04f0b6a.png">

**Comment by donskov** [comment]
Hello @pavsoldatov. Thank you for the report. Please try to use the updated version:
```
 - @peculiar/certificates-viewer-react@3.0.5
 ```
