### ISSUE TITLE
How do I use it with npm?

### ISSUE THREAD

**Issue by ananthb** [PeculiarVentures/pv-certificates-viewer#131]
1. I installed this in my project with `npm install @peculiar/certificates-viewer`. 
2. I also imported it in my ES6 module file that gets loaded by a browser like this `import "@peculiar/certificates-viewer";`.
3. After this, I created a custom element called `<peculiar-certificates-viewer>`.

But nothing happened. How do I include this project through npm?

**Comment by donskov** [comment]
@ananthb Try this:
```ts
import { defineCustomElements } from '@peculiar/certificates-viewer/loader';

defineCustomElements();
```

**Comment by ananthb** [comment]
@donskov that worked perfectly, thank you. I tried poking around and I can't find a place to submit an example using plain Javascript. I'd be happy to, if you want.

I have another issue now. Is there any CSS to load separately? The download buttons are missing. I'm only able to see an empty box when I click the button. The button itself looks a bit weird.

Button closed

<img width="255" alt="Screenshot 2023-09-28 at 21 14 45" src="https://github.com/PeculiarVentures/pv-certificates-viewer/assets/3133350/5ecd8aaa-cfa3-4c9e-8b74-c914b1a9f7c5">

Button open

<img width="229" alt="Screenshot 2023-09-28 at 21 14 58" src="https://github.com/PeculiarVentures/pv-certificates-viewer/assets/3133350/a87c66ec-4a6a-46c9-8dd3-ce6e5ed72bac">

**Comment by donskov** [comment]
@ananthb 
1. You can add usage examples to https://github.com/PeculiarVentures/pv-certificates-viewer/blob/master/packages/webcomponents/README.md.
2. Yes, you should load the root styles:
 - cdn variant.
 ```html
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@peculiar/certificates-viewer/dist/peculiar/peculiar.css">
```
- or load the same file from the `node_modules` directory.

**Comment by donskov** [comment]
@ananthb Added [NPM](https://github.com/PeculiarVentures/pv-certificates-viewer/blob/main/packages/webcomponents/README.md#npm) using an example and released a new version of the components.
