### ISSUE TITLE
Link from readme on npm page of package leads to 404

### ISSUE THREAD

**Issue by p1nta** [PeculiarVentures/pv-certificates-viewer#132]
This link leads to 404

<img width="923" alt="image" src="https://github.com/PeculiarVentures/pv-certificates-viewer/assets/30403859/eca9e189-87e3-48b0-8975-ac0e5f5cbdb9">

**Comment by donskov** [comment]
@p1nta Thanks. Fixed in https://github.com/PeculiarVentures/pv-certificates-viewer/commit/b89749c10ccaa396aa0c18a44ea461b1a5632f2c. Will be available in the next release.
