### ISSUE TITLE
Add optional filter the list vs highlight option

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/pv-certificates-viewer#26]
It would be nice if there was a "search behavior" where choices were "filterandhighligh" or "highlight"

![image](https://user-images.githubusercontent.com/1619279/69751574-40a02580-1104-11ea-80ca-c1d5d4018447.png)

This would make it so you only see matching items vs only highlighting text that matches.

Alternativly could make this the default behavior and not make it an option.

This is a nice to have only and not important.

**Comment by donskov** [comment]
We added new attributes for our component:
- `filterWithSearch: boolean` (by default `true`)
- `highlightWithSearch: boolean` (by default `true`)

**1. `filterWithSearch=true` && `highlightWithSearch=true`**

Without search value

![image](https://user-images.githubusercontent.com/9417251/71078473-22bd6200-2192-11ea-9cca-b43ea68e42a8.png)

With search value

![image](https://user-images.githubusercontent.com/9417251/71078492-31a41480-2192-11ea-8fa8-f7c0b4135235.png)

Without results

![image](https://user-images.githubusercontent.com/9417251/71078523-408ac700-2192-11ea-9dd7-fcb226b259a1.png)

**2. `filterWithSearch=true` && `highlightWithSearch=false`**

Without search value

![image](https://user-images.githubusercontent.com/9417251/71078680-89428000-2192-11ea-9697-d9dcfd1fa375.png)

With search value

![image](https://user-images.githubusercontent.com/9417251/71078702-92335180-2192-11ea-9067-717adda5e617.png)

Without results

![image](https://user-images.githubusercontent.com/9417251/71078722-9a8b8c80-2192-11ea-9dbe-a800263a122d.png)

**3. `filterWithSearch=false` && `highlightWithSearch=true`**

Without search value

![image](https://user-images.githubusercontent.com/9417251/71078775-b98a1e80-2192-11ea-8a7f-01553c728091.png)

With search value

![image](https://user-images.githubusercontent.com/9417251/71078799-c149c300-2192-11ea-81d6-6ae049585364.png)

Without results

![image](https://user-images.githubusercontent.com/9417251/71078815-c870d100-2192-11ea-8f34-93aadc3adcc3.png)

**4. `filterWithSearch=false` && `highlightWithSearch=false`** (for this case we remove search block)

![image](https://user-images.githubusercontent.com/9417251/71078845-d7578380-2192-11ea-8b69-1ef309526b73.png)

@rmhrisk What do you think?
