### ISSUE TITLE
Add example showing displaying a certificate 

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/pv-certificates-viewer#34]
Currently, we have two examples on https://peculiarventures.github.io/pv-certificates-viewer/

It would be nice if there was an example of showing a certificate embedded in the example that did not require the table view.

e.g. we could embed a certificate view.

**Comment by donskov** [comment]
@rmhrisk I added [demo](https://peculiarventures.github.io/pv-certificates-viewer/certificate-viewer-demo.html) and updated links in readme. Could you check?

**Comment by rmhrisk** [comment]
I’m on my phone now but only see the cert view; I was thinking we would show all three views.

**Comment by donskov** [comment]
@rmhrisk Updated. Please check again
