### ISSUE TITLE
in 2 years -> expires in 2 years (date)

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/pv-certificates-viewer#37]
![image](https://user-images.githubusercontent.com/1619279/72571371-43053d00-3874-11ea-8415-c183824049c0.png)

**Comment by donskov** [comment]
@rmhrisk Updated. Now:
![image](https://user-images.githubusercontent.com/9417251/72722360-ce3d4600-3b86-11ea-8e7f-f0ffc4a537ff.png)
![image](https://user-images.githubusercontent.com/9417251/72722371-d6958100-3b86-11ea-8e12-b7da9a138d2d.png)
