### ISSUE TITLE
Update readme with table of options and descriptions 

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/pv-certificates-viewer#40]
We have added a few options such as parent and siblings link. We should update the readme with a table of all
Options.

**Comment by donskov** [comment]
@rmhrisk Can we add the [link](https://github.com/PeculiarVentures/pv-certificates-viewer/tree/master/src/components/certificate-viewer#properties)? Or need to add these options to the main readme?

**Comment by rmhrisk** [comment]
Link to bugs describing is ok.

**Comment by donskov** [comment]
@rmhrisk Added 
![image](https://user-images.githubusercontent.com/9417251/72844355-00dd6080-3ca5-11ea-9746-f3d4b17bd12b.png)
