### ISSUE TITLE
{{subjectKeyId}} should omit the OCTET STRING tag/length

### ISSUE THREAD

**Issue by robstradling** [PeculiarVentures/pv-certificates-viewer#41]
Using this...
```
<pv certificate-viewer
...
subject-key-id-siblings-link="?ski={{subjectKeyId}}">
```
...I get a URL looking like this (for example):
https://crt.sh/?ski=0414c65178c6fd77bee4cc1904c81b1f16fafb9412dc

However, crt.sh needs the leading "0414" to be omitted (for example):
https://crt.sh/?ski=c65178c6fd77bee4cc1904c81b1f16fafb9412dc

Censys has the same issue.  This works...
https://censys.io/certificates?q=parsed.extensions.subject_key_id%3A+c65178c6fd77bee4cc1904c81b1f16fafb9412dc
...but this doesn't...
https://censys.io/certificates/help?q=parsed.extensions.subject_key_id%3A+0414c65178c6fd77bee4cc1904c81b1f16fafb9412dc

**Comment by donskov** [comment]
@robstradling Fixed. Now `{{subjectKeyId}}` value is correct:

![image](https://user-images.githubusercontent.com/9417251/72758905-c4dec880-3bdc-11ea-9952-4a922ff3119c.png)

**Comment by robstradling** [comment]
Excellent.  Thanks @donskov.
