### ISSUE TITLE
Show the timezone for the certificate validity dates

### ISSUE THREAD

**Issue by robstradling** [PeculiarVentures/pv-certificates-viewer#42]
https://crt.sh/?pv=2275659585 (for example) displays the following (for me, anyway):
```
Issued:     Tue, Dec 31, 2019 12:00 AM
Expired:    Fri, Oct 9, 2020 1:00 PM
```
I'm guessing that these timestamps are currently being expressed in the local timezone.  2 thoughts...
1. It would be helpful to indicate the timestamp's timezone in the UI.
2. I personally think that it would be better to always express these timestamps in UTC.

**Comment by donskov** [comment]
@robstradling I changed the date format to UTC. Now the component displays the following:
```
Issued:      Tue, 31 Dec 2019 00:00:00 GMT
Expired:     Fri, 09 Oct 2020 12:00:00 GMT
```

**Comment by robstradling** [comment]
Looks good.  Thanks @donskov.
