### ISSUE TITLE
Add support for Adobe Timestamp Extension

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/pv-certificates-viewer#46]
This certificate https://understandingwebpki.com/?cert=MIIGAzCCBOugAwIBAgIMGzvluEzRrEs%2BIn%2B0MA0GCSqGSIb3DQEBCwUAMEsxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMSEwHwYDVQQDExhHbG9iYWxTaWduIENBIDIgZm9yIEFBVEwwHhcNMTkwMzEyMTU0ODEzWhcNMjIwMzEyMTU0ODEzWjCBjjELMAkGA1UEBhMCR0IxDTALBgNVBAgTBEtlbnQxEjAQBgNVBAcTCU1haWRzdG9uZTEfMB0GA1UEChMWR01PIEdsb2JhbFNpZ24gTGltaXRlZDESMBAGA1UEAxMJTWFya2V0aW5nMScwJQYJKoZIhvcNAQkBFhhtYXJrZXRpbmdAZ2xvYmFsc2lnbi5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDqir7oUH1ih%2FfzhGZMlWmnx3T6fdmC4vnFPb8eSkttoWWseQk1rK%2B1RQvMIxfZO69b%2FmLUSsmXV5Gpe5vXlE9qRxX5svBJAn46JjFbdvQ%2B33Mst8s%2FIRnQO8YXZXUvGyYIR0%2BPHVP8Y4THTPsR%2BLuVhzhiqqi7ErW5QrBV7trEbkJV%2BWfyubmb1gtXAUYx88w%2BA35encBWP50d3E7HUJZ56dq3WLNPtKpee4GVFWVCZfP9ST5zKgpknkaQloUAg3%2BkfEfW7Hnwa%2B4IyzKoY1CWbMr3Yr6U15RKpvog0Vk5JzAouV7xhl34m491uoItb3e2TL77Yu0tJU%2FdSWI7mN1NAgMBAAGjggKhMIICnTAOBgNVHQ8BAf8EBAMCBsAwgYgGCCsGAQUFBwEBBHwwejBBBggrBgEFBQcwAoY1aHR0cDovL3NlY3VyZS5nbG9iYWxzaWduLmNvbS9jYWNlcnQvZ3NhYXRsMnNoYTJnMi5jcnQwNQYIKwYBBQUHMAGGKWh0dHA6Ly9vY3NwMi5nbG9iYWxzaWduLmNvbS9nc2FhdGwyc2hhMmcyMIHbBgNVHSAEgdMwgdAwgc0GCysGAQQBoDIBKB4CMIG9MIGGBggrBgEFBQcCAjB6DHhUaGlzIGNlcnRpZmljYXRlIGhhcyBiZWVuIGlzc3VlZCBpbiBhY2NvcmRhbmNlIHdpdGggdGhlIEdsb2JhbFNpZ24gQ1BTIGxvY2F0ZWQgYXQgaHR0cHM6Ly93d3cuZ2xvYmFsc2lnbi5jb20vcmVwb3NpdG9yeS8wMgYIKwYBBQUHAgEWJmh0dHBzOi8vd3d3Lmdsb2JhbHNpZ24uY29tL3JlcG9zaXRvcnkvMAkGA1UdEwQCMAAwPwYDVR0fBDgwNjA0oDKgMIYuaHR0cDovL2NybC5nbG9iYWxzaWduLmNvbS9ncy9nc2FhdGwyc2hhMmcyLmNybDAjBgNVHREEHDAagRhtYXJrZXRpbmdAZ2xvYmFsc2lnbi5jb20wXAYKKoZIhvcvAQEJAQROMEwCAQGGRGh0dHA6Ly9hYXRsLXRpbWVzdGFtcC5nbG9iYWxzaWduLmNvbS90c2EvYW9oZmV3YXQyMzg5NTM1Zm5hc2dubGc1bTIzAQEAMBMGA1UdJQQMMAoGCCsGAQUFBwMEMB0GA1UdDgQWBBSo9UylHp5UFdCQk8HTUzilpwClJjAfBgNVHSMEGDAWgBTFE07Oh8aJGyPoQON1MpsDcDrv7zANBgkqhkiG9w0BAQsFAAOCAQEASAUDaM8KjiUhPMd0hFwJq11FdkUXnLmMRGGX%2FVEPIwwf27dmmjqk3%2F0Zh2OtR5EZBYSrsoYr7Rc9mKRYIr%2B70zOoRnoQ8GPJDh4guC6D%2BSNVcOl2hcbNPd3sWFf4eeM%2Bum3hXDPvwFRFULvPI%2FnWqyarEJxFIyGFjNOcXcFfUUIDTUUWxwFFKWFUzkyBMUtiaYttRqfHzvfoNXZX92NZatsifzaVLME06I1OoTObNzpY8VOy5IF7lwxMguS12Yfd0pPGDX4dwmWtX0Q7qMqrgl9bB3zUMnVycQ6n%2FCAWcuwdo%2BTD08zP2ztDv7G8Q250t2IAEWQXcbvaEWxwqIgKNQ%3D%3D

Contains an extension (1.2.840.113583.1.1.9.1) who's value is:

 ```
304c0201018644687474703a2f2f6161746c2d74696d657374616d702e676c6f62616c7369676e2e636f6d2f7473612f616f68666577617432333839353335666e6173676e6c67356d3233010100
```

Which is simply Hex of a string, which in this case is:

```
http://aatl-timestamp.globalsign.com/tsa/aohfewat2389535fnasgnlg5m23
```

It would be nice to have this officially supported.

**Comment by donskov** [comment]
Added

![image](https://user-images.githubusercontent.com/9417251/78806627-99919b80-79cb-11ea-99a5-703bec451391.png)

@rmhrisk Please check

**Comment by rmhrisk** [comment]
Works.

https://twitter.com/rmhrisk/status/1247978515607113729?s=20
