### ISSUE TITLE
is there any chance to support vite？

### ISSUE THREAD

**Issue by CoderSiu** [PeculiarVentures/pv-certificates-viewer#79]
hey there，hope this project will support vite.

**Comment by rmhrisk** [comment]
I don’t believe there is anything special needed.  I suspect this is all you need https://vaadin.com/learn/tutorials/using-web-components-in-vue

**Comment by donskov** [comment]
Hello @CoderSiu .
Try to use one of [usage](https://github.com/PeculiarVentures/pv-certificates-viewer/tree/master/packages/webcomponents#installation) method from the readme.
