### ISSUE TITLE
Different rendering at embedded and understandingwebpki.com for same cert 

### ISSUE THREAD

**Issue by WorldThirteen** [PeculiarVentures/pv-certificates-viewer#97]
1. I have embedded the @peculiar/certificate-viewer to my project using `@peculiar/certificates-viewer-react@0.3.9` (latest for the moment of this issue creation), and viewing a certificate:
I see:
![image](https://user-images.githubusercontent.com/14346393/129792463-97e405c2-a8ac-4fd4-b191-49528f60687f.png)

Download it using the embedded button "Download as PEM",
2. drop into https://understandingwebpki.com form, see:
![image](https://user-images.githubusercontent.com/14346393/129792514-767a56b5-3e46-4c43-aa98-ddaba8227018.png).

Notice that the extension has more info in the second case.

I could share the certificate in PM.

I wish the embedded version to render the same info as the one deployed on https://understandingwebpki.com.

**Comment by donskov** [comment]
@WorldThirteen Thanks for the reporting. The problem was related to `instanseof` check.
Try to use `@peculiar/certificates-viewer-react@0.3.11` version.

**Comment by WorldThirteen** [comment]
Fixed.
